#!/usr/bin/env bash
# Installs nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
