#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th itr displays "Hi"

count=0

while [ $count -lt 11 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
  let count+=1
done
