#!/usr/bin/env bash
# cultures with numbers ...

i=1

while [ "$i" -lt 21 ]; do
  
  case "$i" in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac

  ((i++))
done#!/usr/bin/env bash
# display time for 12 hours and 59 minutes

hour=0

while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  
  minute=1
  
  while [ "$minute" -lt 60 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done

  hour=$((hour + 1))
done
